FROM node:22.12.0-bullseye

# Create app directory
WORKDIR /app

# Install app dependencies

COPY package.json .

COPY prisma ./prisma/

RUN npm install

# Bundle app source

COPY . .
# Generate Prisma Client


# Copy entrypoint script
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 3000

# Use entrypoint to run migrations and start the app
ENTRYPOINT ["/app/entrypoint.sh"]