FROM node:22.12.0-alpine

# Create app directory
WORKDIR /app

# Install app dependencies

COPY package.json .

COPY prisma ./prisma/

RUN apk add openssl

# Bundle app source

RUN npm install

COPY . .

RUN npx prisma generate
# Copy entrypoint script
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 5000

# Use entrypoint to run migrations and start the app
ENTRYPOINT ["/app/entrypoint.sh"]